### ISSUE TITLE
importing in typescript project does not work

### ISSUE THREAD

**Issue by CramericaIndustries** [onthegomap/maplibre-contour#72]
I'm trying to use the maplibre-contour library in my typescript file, but I'm getting a compiler error:

> Error: export 'default' (imported as 'mlcontour') was not found in 'maplibre-contour' (module has no exports)

installed it with yarn
`yarn add maplibre-contour --save`

Here is the code snippet:
```
import mlcontour from "maplibre-contour";
import type {
    Map as MapLibreMap
} from 'maplibre-gl';


export abstract class MlContourLines {
    public static addContourLines(map: MapLibreMap) {
        ...
        const contourSource = new mlcontour.DemSource({...});          // this line triggers the compiler error
        ...
    }
}
```

Could it be that the "maplibre-contour" es6 module only exports types and not the actual code?

**Comment by CramericaIndustries** [comment]
using `import mlcontour from "maplibre-contour/dist/index";` seems to work.

**Comment by msbarry** [comment]
Does this work: `import * as mlcontour from "maplibre-contour"` ?

I include these exports in the package.json:

https://github.com/onthegomap/maplibre-contour/blob/37ca663213488058e2b1e58871902e9900908c1d/package.json#L5-L9

that I build using rollup like this:

https://github.com/onthegomap/maplibre-contour/blob/37ca663213488058e2b1e58871902e9900908c1d/rollup.config.js#L40-L43

I'm not quite sure which it's picking up when you do import `"maplibre-contour/dist/index"`, maybe I have the mapping wrong in package.json?

**Comment by CramericaIndustries** [comment]
> using `import mlcontour from "maplibre-contour/dist/index";` seems to work.

Quick update... using that line of code, everything compiles without errors, but then in the browser the following error is thrown...

```
dea5dd08-9496-45e2-97b2-8ef1170e1732:1770 Uncaught ReferenceError: C_tmp_main_nx_monorepo_node_modules_angular_devkit_build_angular_node_modules_babel_runtime_helpers_esm_asyncToGenerator_js__WEBPACK_IMPORTED_MODULE_0__ is not defined
    at dea5dd08-9496-45e2-97b2-8ef1170e1732:1770:176
    at new Actor (dea5dd08-9496-45e2-97b2-8ef1170e1732:1817:8)
    at dea5dd08-9496-45e2-97b2-8ef1170e1732:1897:13
    at dea5dd08-9496-45e2-97b2-8ef1170e1732:1898:3
```

**Comment by CramericaIndustries** [comment]
> import * as mlcontour from "maplibre-contour"

Nope sorry.
```
import * as mlcontour from "maplibre-contour"
...
new mlcontour.default.DemSource({...});
```

still throws...
`Error: export 'default' (imported as 'mlcontour') was not found in 'maplibre-contour' (module has no exports)`

I ended up loading the "maplibre-contour.min.js" file on demand via vanilla javascript and am not using TS typings for the mlcontour lib.

**Comment by msbarry** [comment]
I'm trying to reproduce this issue in a test project to make sure it works in CI - can you see what's different from this test project to yours so I can reproduce the issue? https://github.com/onthegomap/maplibre-contour/tree/test-build/test-project

**Comment by caspg** [comment]
I have a similar issue and found out that the issue is related to `esbuild`. But only when run with `--bundle` option https://esbuild.github.io/api/#bundle

You can run the below command inside the test-project and it should fail.

```bash
npx esbuild index.ts --bundle
```

```
npx esbuild --version
0.19.10

node -v
v20.10.0
```

**Comment by msbarry** [comment]
OK I think I fixed this in #146 - try using version 0.0.6.

**Comment by CramericaIndustries** [comment]
I can confirm that with v0.0.6 the "maplibre-contour" import is now working as expected in my project. Thank you!

**Comment by bdon** [comment]
using publint reports missing types:

https://publint.dev/maplibre-contour@0.0.7

I ended up having to switch to `tsup` or another project to generate `.cjs`, `.cts` etc: https://github.com/protomaps/protomaps-leaflet/pull/163
